[package]
name = "fmt-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.25.9"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
serde_yaml = { version = "0.9" }