name: CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Build
        run: cargo build --verbose

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run Tests
        run: cargo nextest run --all-features

      - name: Run doctests
        run: cargo test --doc

      - name: Generate code coverage report (main)
        if: github.base_ref == 'main' || github.ref == 'refs/heads/main'
        run: cargo llvm-cov --all-features --workspace --fail-under-lines 80

      - name: Generate code coverage report (dev)
        if: github.base_ref == 'dev' || github.ref == 'refs/heads/dev'
        run: cargo llvm-cov --all-features --workspace --fail-under-lines 40
